apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: production

resources:
- ../base
- configmap.yaml
- secret.yaml
- ingress.yaml
- certificate.yaml

images:
- name: ghcr.io/andreabelardi/k8s-lab
  newTag: latest

patches:
- patch: |-
    - op: replace
      path: /spec/replicas
      value: 3
  target:
    kind: Deployment
    name: k8s-lab