name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout codice
        uses: actions/checkout@v4

      - name: Login su GitHub Container Registry
        run: |
          echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} --password-stdin

      - name: Build immagine Docker
        run: |
          docker build -t ghcr.io/andreabelardi/k8s-lab:${{ github.sha }} .
          docker tag ghcr.io/andreabelardi/k8s-lab:${{ github.sha }} ghcr.io/andreabelardi/k8s-lab:latest

      - name: Push immagine su GHCR
        run: |
          docker push ghcr.io/andreabelardi/k8s-lab:${{ github.sha }}
          docker push ghcr.io/andreabelardi/k8s-lab:latest

 